// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateFiveDayRate(arg1:string):Promise<string>;

export function GetStockAnalysis():Promise<string>;

export function GetStockData():Promise<string>;

export function Greet(arg1:string):Promise<string>;
