// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateFiveDayRate(arg1) {
  return window['go']['main']['App']['CalculateFiveDayRate'](arg1);
}

export function GetStockAnalysis() {
  return window['go']['main']['App']['GetStockAnalysis']();
}

export function GetStockData() {
  return window['go']['main']['App']['GetStockData']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
